### ISSUE TITLE
I2C to LCD 16x2

### ISSUE THREAD

**Issue by dalfy15** [ccrause/fpc-avr#5]
Hello. How can I connect the LCD 16x2 via the I2C module?

**Comment by ccrause** [comment]
The current library code directly drives the data and command pins of the LCD.  The procedures from [set_controlPinsOutput](https://github.com/ccrause/fpc-avr/blob/master/src/library/lcd_hd44780.pas#L52) to [lcd_write](https://github.com/ccrause/fpc-avr/blob/master/src/library/lcd_hd44780.pas#L151) needs to be rewritten to pass data over I2C to the LCD module.  Check if the supplier of the module has an Arduino library, it should be relatively easy to convert the I2C code to Pascal and create an LCD version for I2C.

Some boards uses the PCF8574 I2C to I/O expander, this seems really easy to work with, just write the IO line bits to the expander address.  Adafruit sells an I2C expander based on the MCP23008, which requires a bit more configuration to get to work.

**Comment by dalfy15** [comment]
Yes, I've already watched Arduino, but it's hard for me.
Thank you, I will try to translate.

**Comment by ccrause** [comment]
A new unit lcd_hd44780_i2c has been added to support the LCDs with i2c backpacks. Tested with a PCF8574A module and HD44780 LCD only.  See [this example project](https://github.com/ccrause/fpc-avr/tree/master/src/examples/lcd1_i2c) for reference.
